version: '3.4'

services:
  todotask.api:
    image: ${DOCKER_REGISTRY-}todotaskapi
    build:
      context: .
      dockerfile: Services/ToDoTask/Dockerfile

  postgresDb:
    image: postgres

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: Services/Identity/Dockerfile

  todotask.client:
    image: ${DOCKER_REGISTRY-}todotaskclient
    build:
      context: .
      dockerfile: client/Dockerfile.development

volumes:
  db_data:
