version: '3.4'

services:
  todotask.api:
    container_name: todotask.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - 'DatabaseSettings:ConnectionString=Server=postgresDb;Port=5432;Database=db;User Id=admin;Password=admin1234;'
      - 'IdentityServerOrigin=http://identityserver:80'
    depends_on:
      - identityserver
      - postgresDb
    ports:
      - '8000:80'

  postgresDb:
    container_name: postgresDb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=db
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/db/data/

  identityserver:
    container_name: identityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=https://+:443;http://+:80
      - 'ConnectionStrings:IdentityServerConnection=Server=postgresDb;Port=5432;Database=db;User Id=admin;Password=admin1234;'
      - PORT=80
    depends_on:
      - postgresDb
    ports:
      - '8001:80'

  todotask.client:
    container_name: todotaskclient
    ports:
      - '80:80'
    volumes:
      - .:/app
      - /app/node_modules
