apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
stringData:
  RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
  RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
  RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
type: Opaque
