apiVersion: v1
kind: Secret
metadata:
  name: email-secret
type: Opaque
stringData:
  MJ_APIKEY_PRIVATE: ${MJ_APIKEY_PRIVATE}
  MJ_APIKEY_PUBLIC: ${MJ_APIKEY_PUBLIC}
  RABBITMQ_HOSTADDRESS: ${RABBITMQ_HOSTADDRESS}
