apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-deployment
  labels:
    app: task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
        - name: task
          image: asia-southeast1-docker.pkg.dev/refined-veld-398701/todoapps/todotask:latest
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: task-config
                  key: ASPNETCORE_ENVIRONMENT
            - name: ClientOrigin
              valueFrom:
                configMapKeyRef:
                  name: task-config
                  key: ClientOrigin
            - name: IDENTITY_URL
              valueFrom:
                configMapKeyRef:
                  name: task-config
                  key: IDENTITY_URL
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: task-config
                  key: PORT
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: task-secret
                  key: DATABASE_URL
            - name: RABBITMQ_HOSTADDRESS
              valueFrom:
                secretKeyRef:
                  name: task-secret
                  key: RABBITMQ_HOSTADDRESS
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /Health
              port: 80
              scheme: HTTP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /Health
              port: 80
              scheme: HTTP
---
apiVersion: v1
kind: Service
metadata:
  name: task-service
spec:
  selector:
    app: task
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
